name: Generate Animation
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for authentication

      - name: Enable debug logging for Git
        run: |
          echo "GIT_TRACE=1" >> $GITHUB_ENV
          echo "GIT_CURL_VERBOSE=1" >> $GITHUB_ENV

      - name: Set Git user identity
        run: |
          git config user.name "Priyasha-Yadav"
          git config user.email "priyasha.yadav.cg@gmail.com"

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT_TOKEN here

      - name: Verify files in dist directory
        run: |
          ls -la dist

      - name: Check if the generated SVG files exist
        run: |
          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
            echo "Error: github-contribution-grid-snake.svg not found!"
            exit 1
          fi
          if [ ! -f dist/github-contribution-grid-snake-dark.svg ]; then
            echo "Error: github-contribution-grid-snake-dark.svg not found!"
            exit 1
          fi

      - name: Create or switch to the output branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output
          else
            git checkout --orphan output
            git reset --hard
            git commit --allow-empty -m "Initial commit on output branch"
            git push origin output
          fi

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT here

