on:
  schedule:
  - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for consistency

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use SSH key for authentication (make sure you have added it as a secret)

      # Step 2: Enable debug logging for Git (for troubleshooting)
      - name: Enable debug logging for Git
        run: |
          echo "GIT_TRACE=1" >> $GITHUB_ENV
          echo "GIT_CURL_VERBOSE=1" >> $GITHUB_ENV

      # Step 3: Set Git user identity (to avoid errors when making commits)
      - name: Set Git user identity
        run: |
          git config user.name "Priyasha-Yadav"
          git config user.email "priyasha.yadav.cg@gmail.com"

      # Step 4: Generate GitHub Contribution Snake Animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT here for generating the snake SVG

      # Step 5: Verify the generated files in the dist directory
      - name: Verify files in dist directory
        run: |
          ls -la dist  # List files in the dist directory to verify the SVGs

      # Step 6: Check if the generated SVG files exist
      - name: Check if the generated SVG files exist
        run: |
          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
            echo "Error: github-contribution-grid-snake.svg not found!"
            exit 1  # Fail the workflow if the SVG isn't found
          fi
          if [ ! -f dist/github-contribution-grid-snake-dark.svg ]; then
            echo "Error: github-contribution-grid-snake-dark.svg not found!"
            exit 1  # Fail the workflow if the dark SVG isn't found
          fi

      # Step 7: Create or switch to the output branch
      - name: Create or switch to the output branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output  # If the branch exists, switch to it
          else
            git checkout --orphan output  # Create a new orphan branch if it doesn't exist
            git reset --hard
            git commit --allow-empty -m "Initial commit on output branch"  # Make an empty commit if the branch is new
            git push origin output  # Push the new branch to the remote repository
          fi

      # Step 8: Push to output branch using SSH
      - name: Push to output branch
        run: |
          git remote set-url origin git@github.com:Priyasha-Yadav/Priyasha-Yadav.git  # Use SSH for push
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git commit -m "Update contribution snake"
          git push origin output  # Push the changes to the output branch
